/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDisponibilidadesRouteImport } from './routes/_authenticated/disponibilidades'
import { Route as AuthenticatedFluxoSemanalRouteImport } from './routes/_authenticated/fluxo-semanal'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisponibilidadesRoute =
  AuthenticatedDisponibilidadesRouteImport.update({
    id: '/disponibilidades',
    path: '/disponibilidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFluxoSemanalRoute =
  AuthenticatedFluxoSemanalRouteImport.update({
    id: '/fluxo-semanal',
    path: '/fluxo-semanal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/disponibilidades': typeof AuthenticatedDisponibilidadesRoute
  '/fluxo-semanal': typeof AuthenticatedFluxoSemanalRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/disponibilidades': typeof AuthenticatedDisponibilidadesRoute
  '/fluxo-semanal': typeof AuthenticatedFluxoSemanalRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/disponibilidades': typeof AuthenticatedDisponibilidadesRoute
  '/_authenticated/fluxo-semanal': typeof AuthenticatedFluxoSemanalRoute
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/disponibilidades'
    | '/fluxo-semanal'
    | '/importacoes'
    | '/movimentacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/disponibilidades'
    | '/fluxo-semanal'
    | '/importacoes'
    | '/movimentacoes'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/disponibilidades'
    | '/_authenticated/fluxo-semanal'
    | '/_authenticated/importacoes'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disponibilidades': {
      id: '/_authenticated/disponibilidades'
      path: '/disponibilidades'
      fullPath: '/disponibilidades'
      preLoaderRoute: typeof AuthenticatedDisponibilidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo-semanal': {
      id: '/_authenticated/fluxo-semanal'
      path: '/fluxo-semanal'
      fullPath: '/fluxo-semanal'
      preLoaderRoute: typeof AuthenticatedFluxoSemanalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDisponibilidadesRoute: typeof AuthenticatedDisponibilidadesRoute
  AuthenticatedFluxoSemanalRoute: typeof AuthenticatedFluxoSemanalRoute
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDisponibilidadesRoute: AuthenticatedDisponibilidadesRoute,
  AuthenticatedFluxoSemanalRoute: AuthenticatedFluxoSemanalRoute,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
